# Dataset Creation

## Setup and helpers

In [1]:
import os
import time
import shutil
import requests
import pandas as pd
from pathlib import Path
import kagglehub

# -------------------------------------------------------
# 🔑 KAGGLE API TOKEN — paste your KGAT_... token here
# -------------------------------------------------------
os.environ["KAGGLE_API_TOKEN"] = "KGAT_31a6c43f83ddb413688bd27816a112a2"
# -------------------------------------------------------

DATA_DIR = Path("data/all_datasets")
DATA_DIR.mkdir(parents=True, exist_ok=True)

/Users/zenna/miniconda3/envs/DT056A/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; research-bot/1.0)"}
#SCRAPE_DELAY = 1.5  # seconds between scrape requests — be polite

In [3]:
def download_kaggle(data_dictionary, base_path):
    dest = base_path / data_dictionary["folder"]
    dest.mkdir(parents=True, exist_ok=True)
    try:
        cache_path = Path(kagglehub.dataset_download(data_dictionary["link"]))
        copied = []
        for src in cache_path.rglob("*"):
            if src.is_file():
                shutil.copy2(src, dest / src.name)
                copied.append(src.name)
        print(f"{data_dictionary['name']} done.")
        print(f"{len(copied)} file(s): {copied}")
        return dest
    except Exception as e:
        print(f"{e}")
        return None

In [4]:
def preview_dataset(data_dictionary, base_dir, n_rows = 3):
    folder    = base_dir / data_dictionary["folder"]
    csv_files = list(folder.glob("*.csv")) if folder.exists() else []

    print(f"\n{'─'*70}")
    print(f"Dataset : {data_dictionary['name']}")

    dfs = {}
    for csv_file in csv_files:
        try:
            df = pd.read_csv(csv_file)
            dfs[csv_file.name] = df
            print(f"\nFile    : {csv_file.name}")
            print(f"Shape   : {df.shape[0]:,} rows x {df.shape[1]} cols")
            print(f"Columns : {list(df.columns)}")
            display(df.head(n_rows))
        except Exception as e:
            print(f"Error reading {csv_file.name}: {e}")

    return dfs

In [5]:
DATASETS = [
    {
        "name":        "Top Cities Quality of Life Index 2024",
        "link":        "bilalabdulmalik/top-cities-worldwide-quality-of-life-index-2024",
        "folder":      "qol_index_2024",
    },
    {
        "name":        "Average Net Salary (World Cities)",
        "link":        "cityapiio/average-net-salary-after-tax-main-world-cities",
        "folder":      "net_salary",
    },
    {
        "name":        "City Quality of Life Dataset",
        "link":        "orhankaramancode/city-quality-of-life-dataset",
        "folder":      "qol_dataset",
    },
    {
        "name":        "Global Cost of Living",
        "link":        "mvieira101/global-cost-of-living",
        "folder":      "cost_of_living",
    },
    {
        "name":        "World Happiness Report 2024",
        "link":        "ajaypalsinghlo/world-happiness-report-2024",
        "folder":      "happiness_2024",
    },
    {
        "name":        "City Happiness Index 2024",
        "link":        "emirhanai/city-happiness-index-2024",
        "folder":      "city_happiness_2024",
    },
    {
        "name":        "Sunshine Hours for Cities",
        "link":        "bilalwaseer/sunshine-hours-for-cities-around-the-world",
        "folder":      "sunshine_hours",
    },
    {
        "name":        "World Cities Average Temperature",
        "link":        "bilalwaseer/worlds-cities-with-their-average-temperature",
        "folder":      "avg_temperature",
    },
    {
        "name":        "Internet Download Speed 2024",
        "link":        "chayanonc/internet-download-speed-comparison-2024",
        "folder":      "internet_speed_2024",
    },
    {
        "name":        "World Air Quality Index 2024",
        "link":        "kanchana1990/world-air-quality-data-2024-updated",
        "folder":      "air_quality_2024",
    },
    {
        "name":        "World Cities Informations",
        "link":        "juanmah/world-cities",
        "folder":      "world_cities_info",
    }
]

## Dataset download and preview

In [7]:
for d in DATASETS:
    download_kaggle(d, DATA_DIR)

Top Cities Quality of Life Index 2024 done.
1 file(s): ['livable_cities.csv']
Average Net Salary (World Cities) done.
1 file(s): ['cities_average_net_salary_after_tax.19-10-2021.csv']
City Quality of Life Dataset done.
1 file(s): ['uaScoresDataFrame.csv']
Global Cost of Living done.
2 file(s): ['cost-of-living_v2.csv', 'cost-of-living.csv']
World Happiness Report 2024 done.
1 file(s): ['WHR2024.csv']
City Happiness Index 2024 done.
2 file(s): ['test.csv', 'train.csv']
Sunshine Hours for Cities done.
1 file(s): ['Sunshine hours for cities in the world.csv']
World Cities Average Temperature done.
1 file(s): ['worlds all cities with their avg temp - Sheet1.csv']
Internet Download Speed 2024 done.
2 file(s): ['internet_speed_by_city_may2024.csv', 'internet_speed_by_country_may2024.csv']
World Air Quality Index 2024 done.
1 file(s): ['world_air_quality.csv']
World Cities Informations done.
1 file(s): ['worldcities.csv']

In [8]:
for d in DATASETS:
    preview_dataset(d, DATA_DIR)

──────────────────────────────────────────────────────────────────────
Dataset : Top Cities Quality of Life Index 2024

File    : livable_cities.csv
Shape   : 150 rows x 12 cols
Columns : ['Rank', 'City', 'Country', 'Quality of Life Index', 'Purchasing Power Index', 'Safety Index', 'Health Care Index', 'Cost of Living Index', 'Property Price to Income Ratio', 'Traffic Commute Time Index', 'Pollution Index', 'Climate Index']

,Rank,City,Country,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index
0,1,The Hague,Netherlands,223.8,138.9,79.8,80.7,60.2,5.9,21.0,17.5,90.6
1,2,Luxembourg,Luxembourg,220.6,175.9,71.4,76.6,62.0,9.2,27.7,21.6,82.6
2,3,Eindhoven,Netherlands,217.5,139.4,78.1,78.9,62.2,6.0,24.5,19.2,85.4

──────────────────────────────────────────────────────────────────────
Dataset : Average Net Salary (World Cities)

File    : cities_average_net_salary_after_tax.19-10-2021.csv
Shape   : 685 rows x 25 cols
Columns : ['City', ' "Region"', ' "Country"', ' "Average Monthly Net Salary (After Tax)', ' 2010"', ' "Average Monthly Net Salary (After Tax).1', ' 2011"', ' "Average Monthly Net Salary (After Tax).2', ' 2012"', ' "Average Monthly Net Salary (After Tax).3', ' 2013"', ' "Average Monthly Net Salary (After Tax).4', ' 2014"', ' "Average Monthly Net Salary (After Tax).5', ' 2015"', ' "Average Monthly Net Salary (After Tax).6', ' 2016"', ' "Average Monthly Net Salary (After Tax).7', ' 2017"', ' "Average Monthly Net Salary (After Tax).8', ' 2018"', ' "Average Monthly Net Salary (After Tax).9', ' 2019"', ' "Average Monthly Net Salary (After Tax).10', ' 2020"']

,City,"""Region""","""Country""","""Average Monthly Net Salary (After Tax)","2010""","""Average Monthly Net Salary (After Tax).1","2011""","""Average Monthly Net Salary (After Tax).2","2012""","""Average Monthly Net Salary (After Tax).3",...,"""Average Monthly Net Salary (After Tax).6","2016""","""Average Monthly Net Salary (After Tax).7","2017""","""Average Monthly Net Salary (After Tax).8","2018""","""Average Monthly Net Salary (After Tax).9","2019""","""Average Monthly Net Salary (After Tax).10","2020"""
0,New York City,"""New York""","""United States of America""",3300.0,3568.530000,4017.991667,4339.513069,3476.340323,3376.010678,4026.656605,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Washington, D.C.","""District of Columbia""","""United States of America""",2200.0,3365.200744,3700.000000,3981.700000,4573.356667,3479.050000,3900.222222,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,San Francisco,"""California""","""United States of America""",4700.0,2633.333333,4195.428571,4167.538462,3470.000000,4058.783333,4281.510400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

──────────────────────────────────────────────────────────────────────
Dataset : City Quality of Life Dataset

File    : uaScoresDataFrame.csv
Shape   : 266 rows x 21 cols
Columns : ['Unnamed: 0', 'UA_Name', 'UA_Country', 'UA_Continent', 'Housing', 'Cost of Living', 'Startups', 'Venture Capital', 'Travel Connectivity', 'Commute', 'Business Freedom', 'Safety', 'Healthcare', 'Education', 'Environmental Quality', 'Economy', 'Taxation', 'Internet Access', 'Leisure & Culture', 'Tolerance', 'Outdoors']

,Unnamed: 0,UA_Name,UA_Country,UA_Continent,Housing,Cost of Living,Startups,Venture Capital,Travel Connectivity,Commute,...,Safety,Healthcare,Education,Environmental Quality,Economy,Taxation,Internet Access,Leisure & Culture,Tolerance,Outdoors
0,0,Aarhus,Denmark,Europe,6.1315,4.015,2.8270,2.512,3.5360,6.31175,...,9.6165,8.704333,5.3665,7.63300,4.8865,5.0680,8.373,3.1870,9.7385,4.1300
1,1,Adelaide,Australia,Oceania,6.3095,4.692,3.1365,2.640,1.7765,5.33625,...,7.9260,7.936667,5.1420,8.33075,6.0695,4.5885,4.341,4.3285,7.8220,5.5310
2,2,Albuquerque,New Mexico,North America,7.2620,6.059,3.7720,1.493,1.4555,5.05575,...,1.3435,6.430000,4.1520,7.31950,6.5145,4.3460,5.396,4.8900,7.0285,3.5155

──────────────────────────────────────────────────────────────────────
Dataset : Global Cost of Living

File    : cost-of-living_v2.csv
Shape   : 4,956 rows x 58 cols
Columns : ['city', 'country', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'x20', 'x21', 'x22', 'x23', 'x24', 'x25', 'x26', 'x27', 'x28', 'x29', 'x30', 'x31', 'x32', 'x33', 'x34', 'x35', 'x36', 'x37', 'x38', 'x39', 'x40', 'x41', 'x42', 'x43', 'x44', 'x45', 'x46', 'x47', 'x48', 'x49', 'x50', 'x51', 'x52', 'x53', 'x54', 'x55', 'data_quality']

,city,country,x1,x2,x3,x4,x5,x6,x7,x8,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
0,Seoul,South Korea,7.68,53.78,6.15,3.07,4.99,3.93,1.48,0.79,...,110.36,742.54,557.52,2669.12,1731.08,22067.70,10971.90,2689.62,3.47,1
1,Shanghai,China,5.69,39.86,5.69,1.14,4.27,3.98,0.53,0.33,...,123.51,1091.93,569.88,2952.70,1561.59,17746.11,9416.35,1419.87,5.03,1
2,Guangzhou,China,4.13,28.47,4.98,0.85,1.71,3.54,0.44,0.33,...,43.89,533.28,317.45,1242.24,688.05,12892.82,5427.45,1211.68,5.19,1

File    : cost-of-living.csv
Shape   : 4,874 rows x 59 cols
Columns : ['Unnamed: 0', 'city', 'country', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'x20', 'x21', 'x22', 'x23', 'x24', 'x25', 'x26', 'x27', 'x28', 'x29', 'x30', 'x31', 'x32', 'x33', 'x34', 'x35', 'x36', 'x37', 'x38', 'x39', 'x40', 'x41', 'x42', 'x43', 'x44', 'x45', 'x46', 'x47', 'x48', 'x49', 'x50', 'x51', 'x52', 'x53', 'x54', 'x55', 'data_quality']

,Unnamed: 0,city,country,x1,x2,x3,x4,x5,x6,x7,...,x47,x48,x49,x50,x51,x52,x53,x54,x55,data_quality
0,0,Delhi,India,4.90,22.04,4.28,1.84,3.67,1.78,0.48,...,36.26,223.87,133.38,596.16,325.82,2619.46,1068.90,586.35,7.96,1
1,1,Shanghai,China,5.59,40.51,5.59,1.12,4.19,3.96,0.52,...,121.19,1080.07,564.30,2972.57,1532.23,17333.09,9174.88,1382.83,5.01,1
2,2,Jakarta,Indonesia,2.54,22.25,3.50,2.02,3.18,2.19,0.59,...,80.32,482.85,270.15,1117.69,584.37,2694.05,1269.44,483.19,9.15,1

──────────────────────────────────────────────────────────────────────
Dataset : World Happiness Report 2024

File    : WHR2024.csv
Shape   : 143 rows x 11 cols
Columns : ['Country name', 'Ladder score', 'upperwhisker', 'lowerwhisker', 'Explained by: Log GDP per capita', 'Explained by: Social support', 'Explained by: Healthy life expectancy', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Perceptions of corruption', 'Dystopia + residual']

,Country name,Ladder score,upperwhisker,lowerwhisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.741,7.815,7.667,1.844,1.572,0.695,0.859,0.142,0.546,2.082
1,Denmark,7.583,7.665,7.500,1.908,1.520,0.699,0.823,0.204,0.548,1.881
2,Iceland,7.525,7.618,7.433,1.881,1.617,0.718,0.819,0.258,0.182,2.050

──────────────────────────────────────────────────────────────────────
Dataset : City Happiness Index 2024

File    : test.csv
Shape   : 51 rows x 10 cols
Columns : ['City', 'Month', 'Year', 'Decibel_Level', 'Traffic_Density', 'Green_Space_Area', 'Air_Quality_Index', 'Happiness_Score', 'Cost_of_Living_Index', 'Healthcare_Index']

,City,Month,Year,Decibel_Level,Traffic_Density,Green_Space_Area,Air_Quality_Index,Happiness_Score,Cost_of_Living_Index,Healthcare_Index
0,Auckland,January,2030,55,Low,80,40,8.4,110,97
1,Berlin,January,2030,50,Low,60,45,7.9,80,93
2,Cairo,January,2030,75,Very High,15,110,4.1,55,69

File    : train.csv
Shape   : 545 rows x 10 cols
Columns : ['City', 'Month', 'Year', 'Decibel_Level', 'Traffic_Density', 'Green_Space_Area', 'Air_Quality_Index', 'Happiness_Score', 'Cost_of_Living_Index', 'Healthcare_Index']

,City,Month,Year,Decibel_Level,Traffic_Density,Green_Space_Area,Air_Quality_Index,Happiness_Score,Cost_of_Living_Index,Healthcare_Index
0,New York,January,2024,70,High,35,40,6.5,100,80
1,Los Angeles,January,2024,65,Medium,40,50,6.8,90,75
2,Chicago,January,2024,60,Medium,30,55,7.0,85,70

──────────────────────────────────────────────────────────────────────
Dataset : Sunshine Hours for Cities

File    : Sunshine hours for cities in the world.csv
Shape   : 392 rows x 15 cols
Columns : ['Country', 'City', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Year']

,Country,City,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Year
0,Ivory Coast,Gagnoa,183.0,180.0,196.0,188.0,181.0,118.0,97.0,80.0,110.0,155.0,171.0,164.0,1823.0
1,Ivory Coast,Bouaké,242.0,224.0,219.0,194.0,208.0,145.0,104.0,82.0,115.0,170.0,191.0,198.0,2092.0
2,Ivory Coast,Abidjan,223.0,223.0,239.0,214.0,205.0,128.0,137.0,125.0,139.0,215.0,224.0,224.0,2296.0

──────────────────────────────────────────────────────────────────────
Dataset : World Cities Average Temperature

File    : worlds all cities with their avg temp - Sheet1.csv
Shape   : 465 rows x 16 cols
Columns : ['Country', 'City', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Year', 'Ref.']

,Country,City,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Year,Ref.
0,Algeria,Algiers,11.2\n(52.2),11.9\n(53.4),12.8\n(55.0),14.7\n(58.5),17.7\n(63.9),21.3\n(70.3),24.6\n(76.3),25.2\n(77.4),23.2\n(73.8),19.4\n(66.9),15.2\n(59.4),12.1\n(53.8),17.4\n(63.3),[1]
1,Algeria,Tamanrasset,12.8\n(55.0),15.0\n(59.0),18.1\n(64.6),22.2\n(72.0),26.1\n(79.0),28.9\n(84.0),28.7\n(83.7),28.2\n(82.8),26.5\n(79.7),22.4\n(72.3),17.3\n(63.1),13.9\n(57.0),21.7\n(71.1),[2]
2,Algeria,Reggane,16.0\n(60.8),18.2\n(64.8),23.1\n(73.6),27.9\n(82.2),32.2\n(90.0),36.4\n(97.5),39.8\n(103.6),38.4\n(101.1),35.5\n(95.9),29.2\n(84.6),22.0\n(71.6),17.8\n(64.0),28.3\n(82.9),[3]

──────────────────────────────────────────────────────────────────────
Dataset : Internet Download Speed 2024

File    : internet_speed_by_city_may2024.csv
Shape   : 362 rows x 6 cols
Columns : ['city', 'country', 'country_code', 'continent_code', 'internet_type', 'median_speed(mbps)']

,city,country,country_code,continent_code,internet_type,median_speed(mbps)
0,Ar-Rayyan,Qatar,QA,AS,mobile,460.13
1,Doha,Qatar,QA,AS,mobile,335.37
2,Dubai,United Arab Emirates,AE,AS,mobile,330.40

File    : internet_speed_by_country_may2024.csv
Shape   : 328 rows x 5 cols
Columns : ['country', 'country_code', 'continent_code', 'internet_type', 'median_speed(mbps)']

,country,country_code,continent_code,internet_type,median_speed(mbps)
0,Qatar,QA,AS,mobile,329.37
1,United Arab Emirates,AE,AS,mobile,309.77
2,Kuwait,KW,AS,mobile,233.78

──────────────────────────────────────────────────────────────────────
Dataset : World Air Quality Index 2024
Error reading world_air_quality.csv: Error tokenizing data. C error: Expected 2 fields in line 206, saw 3


──────────────────────────────────────────────────────────────────────
Dataset : World Cities Informations

File    : worldcities.csv
Shape   : 48,059 rows x 11 cols
Columns : ['city', 'city_ascii', 'lat', 'lng', 'country', 'iso2', 'iso3', 'admin_name', 'capital', 'population', 'id']

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.687,139.7495,Japan,JP,JPN,Tōkyō,primary,37785000.0,1392685764
1,Jakarta,Jakarta,-6.175,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.610,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604

## Merge

### Preparation

In [ ]:
# Single csv
qol_index           = pd.read_csv(next((DATA_DIR / "qol_index_2024").glob("*.csv")))
net_salary          = pd.read_csv(next((DATA_DIR / "net_salary").glob("*.csv")))
qol_dataset         = pd.read_csv(next((DATA_DIR / "qol_dataset").glob("*.csv")))
cost_of_living      = pd.read_csv(next((DATA_DIR / "cost_of_living").glob("*.csv")))
sunshine_hours      = pd.read_csv(next((DATA_DIR / "sunshine_hours").glob("*.csv")))
avg_temperature     = pd.read_csv(next((DATA_DIR / "avg_temperature").glob("*.csv")))
world_cities_info   = pd.read_csv(next((DATA_DIR / "world_cities_info").glob("*.csv")))

# Multiple csv
happiness_files = list((DATA_DIR / "city_happiness_2024").glob("*.csv"))
happiness_0 = pd.read_csv(happiness_files[0])
happiness_1 = pd.read_csv(happiness_files[1])
happiness = pd.concat([happiness_0, happiness_1], ignore_index=True)

cost_of_living_files = list((DATA_DIR / "cost_of_living").glob("*.csv"))
cost_of_living = pd.read_csv(cost_of_living_files[0])

internet_speed_files = list((DATA_DIR / "internet_speed_2024").glob("*.csv"))
internet_speed = pd.read_csv(internet_speed_files[0])

dfs = [
    qol_index,
    net_salary,
    qol_dataset,
    cost_of_living,
    sunshine_hours,
    avg_temperature,
    world_cities_info,
    happiness,
    cost_of_living,
    internet_speed,
]

In [10]:
# Prepare the column city and remove useless column
for df in dfs:
    df.columns = df.columns.str.lower()
    df.rename(columns={"ua_name": "city",
                       "ua_country": "country"}, inplace=True)
    try: df.drop(columns=["unnamed: 0"], inplace=True)
    except KeyError as e:
        pass

# Add prefix to datasets with equal column name
sunshine_hours.columns = "sun_" + sunshine_hours.columns
sunshine_hours.rename(columns={"sun_city": "city"}, inplace=True)
sunshine_hours.rename(columns={"sun_country": "country"}, inplace=True)

avg_temperature.columns = "temp_" + avg_temperature.columns
avg_temperature.rename(columns={"temp_city": "city"}, inplace=True)
avg_temperature.rename(columns={"temp_country": "country"}, inplace=True)

happiness.columns = "happy_" + happiness.columns
happiness.rename(columns={"happy_city": "city"}, inplace=True)

### Merging qol

In [11]:
conversion = {
    ' Denmark': 'Denmark',
    ' Australia': 'Australia',
    ' New Mexico': 'United States',
    ' Kazakhstan': 'Kazakhstan',
    ' Netherlands': 'Netherlands',
    ' Alaska': 'United States',
    'Andorra': 'Andorra',
    ' Turkey': 'Turkey',
    ' North Carolina': 'United States',
    ' Paraguay': 'Paraguay',
    ' Greece': 'Greece',
    ' Georgia': 'Georgia',
    ' New Zealand': 'New Zealand',
    ' Texas': 'United States',
    ' Azerbaijan': 'Azerbaijan',
    ' Indonesia': 'Indonesia',
    ' Maryland': 'United States',
    ' Thailand': 'Thailand',
    ' Spain': 'Spain',
    ' China': 'China',
    ' Lebanon': 'Lebanon',
    ' United Kingdom': 'United Kingdom',
    ' Serbia': 'Serbia',
    ' Belize': 'Belize',
    ' India': 'India',
    ' Norway': 'Norway',
    ' Germany': 'Germany',
    ' Switzerland': 'Switzerland',
    ' Alabama': 'United States',
    ' Colombia': 'Colombia',
    ' Idaho': 'United States',
    ' Italy': 'Italy',
    ' France': 'France',
    ' Massachusetts': 'United States',
    ' Colorado': 'United States',
    ' Montana': 'United States',
    ' Slovakia': 'Slovakia',
    ' Czechia': 'Czechia',
    ' Belgium': 'Belgium',
    ' Romania': 'Romania',
    ' Hungary': 'Hungary',
    ' Argentina': 'Argentina',
    ' New York': 'United States',
    ' Egypt': 'Egypt',
    ' Canada': 'Canada',
    ' South Africa': 'South Africa',
    ' Venezuela': 'Venezuela',
    ' Morocco': 'Morocco',
    ' South Carolina': 'United States',
    ' Tennessee': 'United States',
    ' Illinois': 'United States',
    ' Moldova': 'Moldova',
    ' Ohio': 'United States',
    ' Ireland': 'Ireland',
    ' Brazil': 'Brazil',
    ' Tanzania': 'Tanzania',
    ' Iowa': 'United States',
    ' Michigan': 'United States',
    ' Qatar': 'Qatar',
    ' United Arab Emirates': 'United Arab Emirates',
    ' Oregon': 'United States',
    ' Japan': 'Japan',
    ' Poland': 'Poland',
    ' Gibraltar': 'Gibraltar',
    ' Sweden': 'Sweden',
    ' Mexico': 'Mexico',
    ' Guatemala': 'Guatemala',
    ' Cuba': 'Cuba',
    ' Finland': 'Finland',
    ' Vietnam': 'Vietnam',
    ' Hong Kong': 'Hong Kong',
    ' Hawaii': 'United States',
    ' Indiana': 'United States',
    ' Austria': 'Austria',
    ' Florida': 'United States',
    ' Missouri': 'United States',
    ' Nepal': 'Nepal',
    ' Ukraine': 'Ukraine',
    ' Jamaica': 'Jamaica',
    ' Malaysia': 'Malaysia',
    ' Nigeria': 'Nigeria',
    ' Bolivia': 'Bolivia',
    ' Nevada': 'United States',
    ' Peru': 'Peru',
    ' Portugal': 'Portugal',
    ' Slovenia': 'Slovenia',
    ' California': 'United States',
    ' Kentucky': 'United States',
    ' Luxembourg': 'Luxembourg',
    ' Wisconsin': 'United States',
    ' Nicaragua': 'Nicaragua',
    ' Philippines': 'Philippines',
    ' Minnesota': 'United States',
    ' Belarus': 'Belarus',
    ' Uruguay': 'Uruguay',
    ' Russia': 'Russia',
    ' Kenya': 'Kenya',
    ' Louisiana': 'United States',
    ' Cyprus': 'Cyprus',
    ' Oklahoma': 'United States',
    ' Nebraska': 'United States',
    ' Panama': 'Panama',
    ' Pennsylvania': 'United States',
    ' Cambodia': 'Cambodia',
    ' Arizona': 'United States',
    ' Maine': 'United States',
    ' Rhode Island': 'United States',
    ' Ecuador': 'Ecuador',
    ' Iceland': 'Iceland',
    ' Virginia': 'United States',
    ' Latvia': 'Latvia',
    ' Saudi Arabia': 'Saudi Arabia',
    ' Utah': 'United States',
    ' Costa Rica': 'Costa Rica',
    ' Puerto Rico': 'Puerto Rico',
    ' El Salvador': 'El Salvador',
    ' Chile': 'Chile',
    ' Dominican Republic': 'Dominican Republic',
    ' Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    ' Washington': 'United States',
    ' Singapore': 'Singapore',
    ' Macedonia': 'North Macedonia',
    ' Bulgaria': 'Bulgaria',
    ' Taiwan': 'Taiwan',
    ' Estonia': 'Estonia',
    ' Uzbekistan': 'Uzbekistan',
    ' Iran': 'Iran',
    ' Israel': 'Israel',
    ' Tunisia': 'Tunisia',
    ' Malta': 'Malta',
    ' Lithuania': 'Lithuania',
    ' District of Columbia': 'United States',
    ' Armenia': 'Armenia',
    ' Croatia': 'Croatia',
    ' South Korea': 'South Korea',
}

In [12]:
# Fix some namings
for df in [qol_index, qol_dataset]:
    df.replace({
        "city": {
            "Bengaluru":             "Bangalore",
            "Krakow (Cracow)":       "Krakow",
            "Tel Aviv-Yafo":         "Tel Aviv",
            "San Francisco Bay Area": "San Francisco",
            "Tampa Bay Area":        "Tampa",
            "Panama City":           "Panama",

        },
        "country": conversion
        }, inplace=True)

qol_dataset.loc[qol_dataset['city'] == 'Atlanta', 'country'] = 'United States'

In [13]:
qol_dataset[qol_dataset["city"] == "Portland"]

,city,country,ua_continent,housing,cost of living,startups,venture capital,travel connectivity,commute,business freedom,safety,healthcare,education,environmental quality,economy,taxation,internet access,leisure & culture,tolerance,outdoors
191,Portland,United States,North America,0.000,0.000,3.637,0.000,1.1020,1.97025,8.671,6.3585,5.174667,3.6245,7.6755,6.5145,4.0620,3.5465,3.3050,8.2710,4.978
192,Portland,United States,North America,4.138,4.924,6.957,5.899,2.2405,4.90800,8.671,5.1805,6.317667,4.2155,8.4595,6.5145,3.9205,5.9685,6.2195,8.1595,6.304

In [14]:
qol_dataset.drop(191, inplace=True)
qol_dataset.reset_index(drop=True, inplace=True)

qol_dataset[qol_dataset["city"] == "Portland"]

,city,country,ua_continent,housing,cost of living,startups,venture capital,travel connectivity,commute,business freedom,safety,healthcare,education,environmental quality,economy,taxation,internet access,leisure & culture,tolerance,outdoors
191,Portland,United States,North America,4.138,4.924,6.957,5.899,2.2405,4.908,8.671,5.1805,6.317667,4.2155,8.4595,6.5145,3.9205,5.9685,6.2195,8.1595,6.304

In [15]:
qol_index.replace({
    "country": {
        'UnitedStates':         'United States',
        'UnitedArabEmirates':   'United Arab Emirates',
        'UnitedKingdom':        'United Kingdom',
        'NewZealand':           'New Zealand',
        'CzechRepublic':        'Czechia',
        'SaudiArabia':          'Saudi Arabia',
        'SouthAfrica':          'South Africa',
        'SouthKorea':           'South Korea',
        'HongKong(China)':      'Hong Kong',
        'Pakistan':             'Pakistan',
        'BosniaAndHerzegovina': 'Bosnia and Herzegovina',
        'NorthMacedonia':       'North Macedonia',
    }}, inplace=True)

In [16]:
qol_dataset.columns

Index(['city', 'country', 'ua_continent', 'housing', 'cost of living',
       'startups', 'venture capital', 'travel connectivity', 'commute',
       'business freedom', 'safety', 'healthcare', 'education',
       'environmental quality', 'economy', 'taxation', 'internet access',
       'leisure & culture', 'tolerance', 'outdoors'],
      dtype='object')

In [17]:
qol_index.columns

Index(['rank', 'city', 'country', 'quality of life index',
       'purchasing power index', 'safety index', 'health care index',
       'cost of living index', 'property price to income ratio',
       'traffic commute time index', 'pollution index', 'climate index'],
      dtype='object')

In [18]:
# Merge the two datasets
merged_df = pd.merge(
       qol_dataset[['city', 'country', 'housing',
                    'cost of living', 'startups', 'venture capital', 'travel connectivity',
                    'commute', 'business freedom', 'safety', 'healthcare', 'education',
                    'environmental quality', 'economy', 'taxation', 'internet access',
                    'leisure & culture', 'tolerance', 'outdoors']], 
       qol_index[['city', 'country', 'quality of life index',
                  'purchasing power index', 'safety index', 'health care index',
                  'cost of living index', 'property price to income ratio',
                  'traffic commute time index', 'pollution index', 'climate index']], 
       on=["city", "country"], how="outer")

merged_df

,city,country,housing,cost of living,startups,venture capital,travel connectivity,commute,business freedom,safety,...,outdoors,quality of life index,purchasing power index,safety index,health care index,cost of living index,property price to income ratio,traffic commute time index,pollution index,climate index
0,Aarhus,Denmark,6.1315,4.015,2.8270,2.512,3.5360,6.31175,9.940000,9.6165,...,4.1300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abu Dhabi,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,192.4,160.5,88.2,71.1,54.1,5.8,32.9,46.9,43.9
2,Adelaide,Australia,6.3095,4.692,3.1365,2.640,1.7765,5.33625,9.399667,7.9260,...,5.5310,189.4,109.3,67.7,73.9,76.0,7.9,35.5,24.3,95.0
3,Ahmedabad,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,124.5,63.4,67.9,67.2,22.8,7.9,39.0,72.5,49.3
4,Albuquerque,United States,7.2620,6.059,3.7720,1.493,1.4555,5.05575,8.671000,1.3435,...,3.5155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,Winnipeg,Canada,7.5525,5.882,3.7965,0.000,1.4755,5.10450,8.966000,6.0155,...,4.2430,142.3,97.4,39.7,68.4,63.4,6.2,31.3,35.7,24.7
286,Wroclaw,Poland,8.4520,8.434,3.5860,2.386,2.2445,4.95475,5.704333,8.1655,...,4.0850,147.8,88.9,73.8,57.4,42.5,11.2,34.0,61.9,78.4
287,Yerevan,Armenia,9.6945,9.431,3.9265,0.000,1.7870,5.64925,6.501000,8.8730,...,7.7765,116.8,34.0,77.7,57.3,42.1,20.1,29.8,60.7,63.4
288,Zagreb,Croatia,8.9100,7.194,4.4530,1.775,2.0280,4.83000,5.720333,8.6575,...,4.8090,172.0,83.1,78.7,65.1,46.8,12.2,30.0,33.3,82.2
289,Zurich,Switzerland,1.4730,1.000,6.2035,3.872,7.7335,5.83950,8.888000,9.0665,...,5.4010,208.1,181.2,77.2,70.3,100.4,12.9,38.1,24.4,81.5

In [19]:
merged_df[merged_df["city"].duplicated()]["city"].values

array(['Birmingham'], dtype=object)

In [20]:
merged_df[merged_df["city"] == "Birmingham"]

,city,country,housing,cost of living,startups,venture capital,travel connectivity,commute,business freedom,safety,...,outdoors,quality of life index,purchasing power index,safety index,health care index,cost of living index,property price to income ratio,traffic commute time index,pollution index,climate index
33,Birmingham,United Kingdom,5.9035,5.814,4.3575,2.541,5.8450,5.49350,8.992,6.9465,...,1.2675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Birmingham,United States,6.5555,5.133,4.3575,1.000,1.4355,2.02075,8.671,1.7760,...,1.2660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

To avoid complications, Birmingham (US) will be removed

In [21]:
merged_df.drop(34, inplace=True)
merged_df.reset_index(drop=True, inplace=True)

merged_df[merged_df["city"] == "Birmingham"]

,city,country,housing,cost of living,startups,venture capital,travel connectivity,commute,business freedom,safety,...,outdoors,quality of life index,purchasing power index,safety index,health care index,cost of living index,property price to income ratio,traffic commute time index,pollution index,climate index
33,Birmingham,United Kingdom,5.9035,5.814,4.3575,2.541,5.845,5.4935,8.992,6.9465,...,1.2675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
merged_df.columns

Index(['city', 'country', 'housing', 'cost of living', 'startups',
       'venture capital', 'travel connectivity', 'commute', 'business freedom',
       'safety', 'healthcare', 'education', 'environmental quality', 'economy',
       'taxation', 'internet access', 'leisure & culture', 'tolerance',
       'outdoors', 'quality of life index', 'purchasing power index',
       'safety index', 'health care index', 'cost of living index',
       'property price to income ratio', 'traffic commute time index',
       'pollution index', 'climate index'],
      dtype='object')

In [23]:
print(merged_df.shape)
merged_df.isnull().sum()

(289, 28)

city                                0
country                             0
housing                            25
cost of living                     25
startups                           25
venture capital                    25
travel connectivity                25
commute                            25
business freedom                   25
safety                             25
healthcare                         25
education                          25
environmental quality              25
economy                            25
taxation                           25
internet access                    25
leisure & culture                  25
tolerance                          25
outdoors                           25
quality of life index             139
purchasing power index            139
safety index                      139
health care index                 139
cost of living index              139
property price to income ratio    139
traffic commute time index        139
pollution index                   139
climate index                     139
dtype: int64

In [24]:
merged_df["city"].tolist()

['Aarhus',
 'Abu Dhabi',
 'Adelaide',
 'Ahmedabad',
 'Albuquerque',
 'Almaty',
 'Amman',
 'Amsterdam',
 'Anchorage',
 'Andorra',
 'Ankara',
 'Asheville',
 'Asuncion',
 'Athens',
 'Atlanta',
 'Auckland',
 'Austin',
 'Baku',
 'Bali',
 'Baltimore',
 'Bangalore',
 'Bangkok',
 'Barcelona',
 'Beijing',
 'Beirut',
 'Belfast',
 'Belgrade',
 'Belize City',
 'Belo Horizonte',
 'Bergen',
 'Berlin',
 'Bern',
 'Bilbao',
 'Birmingham',
 'Bogota',
 'Boise',
 'Bologna',
 'Bordeaux',
 'Boston',
 'Boulder',
 'Bozeman',
 'Brasilia',
 'Bratislava',
 'Brighton',
 'Brisbane',
 'Bristol',
 'Brno',
 'Brussels',
 'Bucharest',
 'Budapest',
 'Buenos Aires',
 'Buffalo',
 'Cairo',
 'Calgary',
 'Cambridge',
 'Canberra',
 'Cape Town',
 'Caracas',
 'Cardiff',
 'Casablanca',
 'Charleston',
 'Charlotte',
 'Chattanooga',
 'Chennai',
 'Chiang Mai',
 'Chicago',
 'Chisinau',
 'Christchurch',
 'Cincinnati',
 'Cleveland',
 'Cluj-Napoca',
 'Cologne',
 'Colorado Springs',
 'Columbus',
 'Copenhagen',
 'Cork',
 'Curitiba',
 'Dallas',
 'Dar es Salaam',
 'Delhi',
 'Denver',
 'Des Moines',
 'Detroit',
 'Doha',
 'Dresden',
 'Dubai',
 'Dublin',
 'Durban',
 'Dusseldorf',
 'Edinburgh',
 'Edmonton',
 'Eindhoven',
 'Eugene',
 'Florence',
 'Florianopolis',
 'Fort Collins',
 'Frankfurt',
 'Fukuoka',
 'Galway',
 'Gdansk',
 'Geneva',
 'Gibraltar',
 'Glasgow',
 'Gothenburg',
 'Grenoble',
 'Guadalajara',
 'Guatemala City',
 'Gurgaon',
 'Halifax',
 'Hamburg',
 'Hannover',
 'Havana',
 'Helsinki',
 'Ho Chi Minh City',
 'Hong Kong',
 'Honolulu',
 'Houston',
 'Hyderabad',
 'Indianapolis',
 'Innsbruck',
 'Islamabad',
 'Istanbul',
 'Izmir',
 'Jacksonville',
 'Jakarta',
 'Jeddah',
 'Johannesburg',
 'Kansas City',
 'Karlsruhe',
 'Kathmandu',
 'Kiev',
 'Kingston',
 'Knoxville',
 'Kolkata',
 'Krakow',
 'Kuala Lumpur',
 'Kuwait City',
 'Kyoto',
 'La Paz',
 'Lagos',
 'Las Palmas de Gran Canaria',
 'Las Vegas',
 'Lausanne',
 'Leeds',
 'Leipzig',
 'Lille',
 'Lima',
 'Limassol',
 'Lisbon',
 'Liverpool',
 'Ljubljana',
 'London',
 'Los Angeles',
 'Louisville',
 'Luxembourg',
 'Lviv',
 'Lyon',
 'Madison',
 'Madrid',
 'Malaga',
 'Malmo',
 'Managua',
 'Manchester',
 'Manila',
 'Marseille',
 'Medellin',
 'Melbourne',
 'Memphis',
 'Mexico City',
 'Miami',
 'Milan',
 'Milwaukee',
 'Minneapolis-Saint Paul',
 'Minsk',
 'Monterrey',
 'Montevideo',
 'Montreal',
 'Moscow',
 'Mumbai',
 'Munich',
 'Muscat',
 'Nairobi',
 'Nantes',
 'Naples',
 'Nashville',
 'New Orleans',
 'New York',
 'Nice',
 'Nicosia',
 'Nizhny Novgorod',
 'Novi Sad',
 'Odessa (Odesa)',
 'Oklahoma City',
 'Omaha',
 'Orlando',
 'Osaka',
 'Oslo',
 'Ottawa',
 'Oulu',
 'Oxford',
 'Palo Alto',
 'Panama',
 'Paris',
 'Perth',
 'Philadelphia',
 'Phnom Penh',
 'Phoenix',
 'Phuket',
 'Pittsburgh',
 'Portland',
 'Porto',
 'Porto Alegre',
 'Poznan',
 'Prague',
 'Pretoria',
 'Providence',
 'Pune',
 'Quebec',
 'Quito',
 'Raleigh',
 'Reykjavik',
 'Richmond',
 'Riga',
 'Rio De Janeiro',
 'Riyadh',
 'Rochester',
 'Rome',
 'Rotterdam',
 'Saint Petersburg',
 'Salt Lake City',
 'San Antonio',
 'San Diego',
 'San Francisco',
 'San Jose',
 'San Juan',
 'San Luis Obispo',
 'San Salvador',
 'Santiago',
 'Santo Domingo',
 'Sao Paulo',
 'Sarajevo',
 'Saskatoon',
 'Seattle',
 'Seoul',
 'Seville',
 'Shanghai',
 'Singapore',
 'Skopje',
 'Sofia',
 'Split',
 'St. Louis',
 'Stockholm',
 'Stuttgart',
 'Sydney',
 'Taipei',
 'Tallinn',
 'Tampa',
 'Tampere',
 'Tartu',
 'Tashkent',
 'Tbilisi',
 'Tehran',
 'Tel Aviv',
 'The Hague',
 'Thessaloniki',
 'Timisoara',
 'Tokyo',
 'Toronto',
 'Toulouse',
 'Tunis',
 'Turin',
 'Turku',
 'Uppsala',
 'Utrecht',
 'Valencia',
 'Valletta',
 'Vancouver',
 'Varna',
 'Victoria',
 'Vienna',
 'Vilnius',
 'Warsaw',
 'Washington',
 'Wellington',
 'Winnipeg',
 'Wroclaw',
 'Yerevan',
 'Zagreb',
 'Zurich']

### Merging with Informations

In [25]:
world_cities_info.columns

Index(['city', 'city_ascii', 'lat', 'lng', 'country', 'iso2', 'iso3',
       'admin_name', 'capital', 'population', 'id'],
      dtype='object')

In [26]:
world_cities_info.replace(
    {"city_ascii": {
        'Andorra la Vella': 'Andorra',
        'Caerdydd':         'Cardiff',
        'Kyiv':             'Kiev',
        'Las Palmas':       'Las Palmas de Gran Canaria',
        'Minneapolis':      'Minneapolis-Saint Paul',
        "Nizhniy Novgorod": "Nizhny Novgorod",
        "Odesa":            "Odessa (Odesa)",
        'Panama City':      'Panama',
        'Quebec City':      'Quebec',
        'Rio de Janeiro':   'Rio De Janeiro',
        'Sevilla':          'Seville',
        'Tel Aviv-Yafo':    'Tel Aviv',
        'Denpasar':         'Bali'
        },
    "country": {"Korea, South": "South Korea"}}, inplace=True)

In [27]:
us = ['Austin', 'Boston', 'Buffalo', 'Charleston', 'Charlotte',
       'Cleveland', 'Columbus', 'Dallas', 'Des Moines', 'Jacksonville',
       'Kansas City', 'Las Vegas', 'Louisville', 'Madison', 'Memphis',
       'Miami', 'Portland', 'Providence', 'Richmond', 'Rochester',
       'Salt Lake City', 'San Antonio', 'San Diego', 'San Francisco',
       'Washington']

In [28]:
df_us  = merged_df[merged_df["city"].isin(us)]
df_world = merged_df[~merged_df["city"].isin(us)]

#### Cities of the World

In [29]:
df_world.shape

(264, 28)

In [30]:
df_world = pd.merge(df_world, world_cities_info[['city_ascii', 'lat', 
        'lng', 'country', 'iso3','population']], left_on=["city", "country"], right_on=["city_ascii", "country"], how="left")

df_world.shape

(265, 33)

In [31]:
df_world[df_world["city"]== "Uppsala"]

,city,country,housing,cost of living,startups,venture capital,travel connectivity,commute,business freedom,safety,...,cost of living index,property price to income ratio,traffic commute time index,pollution index,climate index,city_ascii,lat,lng,iso3,population
248,Uppsala,Sweden,7.16,5.442,1.4285,0.0,4.7485,5.975,9.569,7.85,...,NaN,NaN,NaN,NaN,NaN,Uppsala,59.8498,17.6389,SWE,174982.0
249,Uppsala,Sweden,7.16,5.442,1.4285,0.0,4.7485,5.975,9.569,7.85,...,NaN,NaN,NaN,NaN,NaN,Uppsala,59.8601,17.6400,SWE,133117.0

In [32]:
df_world.drop(249, inplace=True)

df_world.reset_index(drop=True, inplace=True)

df_world.shape

(264, 33)

In [33]:
df_world.isnull().sum()

city                                0
country                             0
housing                            25
cost of living                     25
startups                           25
venture capital                    25
travel connectivity                25
commute                            25
business freedom                   25
safety                             25
healthcare                         25
education                          25
environmental quality              25
economy                            25
taxation                           25
internet access                    25
leisure & culture                  25
tolerance                          25
outdoors                           25
quality of life index             124
purchasing power index            124
safety index                      124
health care index                 124
cost of living index              124
property price to income ratio    124
traffic commute time index        124
pollution index                   124
climate index                     124
city_ascii                          0
lat                                 0
lng                                 0
iso3                                0
population                          0
dtype: int64

#### Cities in the USA

In [34]:
df_us.shape

(25, 28)

In [35]:
city_to_state = {
    'Austin': 'Texas',
    'Boston': 'Massachusetts',
    'Buffalo': 'New York',
    'Charleston': 'South Carolina',
    'Charlotte': 'North Carolina',
    'Cleveland': 'Ohio',
    'Columbus': 'Ohio',
    'Dallas': 'Texas',
    'Des Moines': 'Iowa',
    'Jacksonville': 'Florida',
    'Kansas City': 'Missouri',
    'Las Vegas': 'Nevada',
    'Louisville': 'Kentucky',
    'Madison': 'Wisconsin',
    'Memphis': 'Tennessee',
    'Miami': 'Florida',
    'Portland': 'Oregon',
    'Providence': 'Rhode Island',
    'Richmond': 'Virginia',
    'Rochester': 'New York',
    'Salt Lake City': 'Utah',
    'San Antonio': 'Texas',
    'San Diego': 'California',
    'San Francisco': 'California',
    'Washington': 'District of Columbia',
}

In [36]:
df_us["admin_name"] = df_us["city"].map(city_to_state)

/var/folders/vx/wsv0__k15g37xmltv38_43l80000gn/T/ipykernel_49188/2331017794.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_us["admin_name"] = df_us["city"].map(city_to_state)

In [37]:
#df_us["country"] = df_us["city"].map(city_to_state)

In [38]:
df_us = pd.merge(df_us, world_cities_info[['city_ascii', 'lat', 
        'lng', 'country', 'iso3','population', 'admin_name']], 
        left_on=["city", "country", "admin_name"], 
        right_on=["city_ascii", "country", "admin_name"], how="left")

df_us.shape

(25, 34)

In [39]:
df_us.drop(columns=["admin_name"], inplace=True)

In [40]:
df_us.isnull().sum()

city                               0
country                            0
housing                            0
cost of living                     0
startups                           0
venture capital                    0
travel connectivity                0
commute                            0
business freedom                   0
safety                             0
healthcare                         0
education                          0
environmental quality              0
economy                            0
taxation                           0
internet access                    0
leisure & culture                  0
tolerance                          0
outdoors                           0
quality of life index             15
purchasing power index            15
safety index                      15
health care index                 15
cost of living index              15
property price to income ratio    15
traffic commute time index        15
pollution index                   15
climate index                     15
city_ascii                         0
lat                                0
lng                                0
iso3                               0
population                         0
dtype: int64

#### Unified dataset

In [41]:
merged_df = pd.concat([df_world, df_us], ignore_index=True)

In [42]:
print(merged_df.shape)

merged_df.isnull().sum()

(289, 33)

city                                0
country                             0
housing                            25
cost of living                     25
startups                           25
venture capital                    25
travel connectivity                25
commute                            25
business freedom                   25
safety                             25
healthcare                         25
education                          25
environmental quality              25
economy                            25
taxation                           25
internet access                    25
leisure & culture                  25
tolerance                          25
outdoors                           25
quality of life index             139
purchasing power index            139
safety index                      139
health care index                 139
cost of living index              139
property price to income ratio    139
traffic commute time index        139
pollution index                   139
climate index                     139
city_ascii                          0
lat                                 0
lng                                 0
iso3                                0
population                          0
dtype: int64

### Merging with Global Cost of Living

In [43]:
conversion_dict = {
    "city":    "city",
    "country": "country",
    # Restaurants
    "x1":  "meal_inexpensive_restaurant",
    "x2":  "meal_midrange_restaurant_for2",
    "x3":  "mcmeal_combo",
    "x4":  "domestic_beer_restaurant",
    "x5":  "imported_beer_restaurant",
    "x6":  "cappuccino",
    "x7":  "coke_pepsi",
    "x8":  "water_restaurant",
    # Markets (groceries)
    "x9":  "milk_1l",
    "x10": "bread_500g",
    "x11": "rice_1kg",
    "x12": "eggs_12",
    "x13": "local_cheese_1kg",
    "x14": "chicken_fillets_1kg",
    "x15": "beef_1kg",
    "x16": "apples_1kg",
    "x17": "banana_1kg",
    "x18": "oranges_1kg",
    "x19": "tomato_1kg",
    "x20": "potato_1kg",
    "x21": "onion_1kg",
    "x22": "lettuce_1head",
    "x23": "water_1_5l_market",
    "x24": "wine_midrange_bottle",
    "x25": "domestic_beer_market",
    "x26": "imported_beer_market",
    "x27": "cigarettes_20pack",
    # Transportation
    "x28": "transport_one_way_ticket",
    "x29": "transport_monthly_pass",
    "x30": "taxi_start",
    "x31": "taxi_1km",
    "x32": "taxi_1hr_waiting",
    "x33": "gasoline_1l",
    "x34": "car_vw_golf",
    "x35": "car_toyota_corolla",
    # Utilities
    "x36": "utilities_85m2",
    "x37": "mobile_tariff_1min",
    "x38": "internet_60mbps",
    # Sports & Leisure
    "x39": "fitness_club_monthly",
    "x40": "tennis_court_1hr",
    "x41": "cinema_ticket",
    # Childcare
    "x42": "preschool_monthly",
    "x43": "international_primary_school_yearly",
    # Clothing
    "x44": "jeans_levis",
    "x45": "summer_dress",
    "x46": "nike_running_shoes",
    "x47": "leather_business_shoes",
    # Rent
    "x48": "rent_1br_city_centre",
    "x49": "rent_1br_outside_centre",
    "x50": "rent_3br_city_centre",
    "x51": "rent_3br_outside_centre",
    # Buy Apartment
    "x52": "price_per_m2_city_centre",
    "x53": "price_per_m2_outside_centre",
    # Salary & Finance
    "x54": "avg_monthly_net_salary",
    "x55": "mortgage_interest_rate",
}

In [44]:
cost_of_living.rename(columns=conversion_dict, inplace=True)

In [45]:
cost_of_living["city"].unique()

array(['Seoul', 'Shanghai', 'Guangzhou', ..., 'Ixtapa Zihuatanejo',
       'Iqaluit', 'Neiafu'], shape=(4898,), dtype=object)

In [46]:
merged_df = pd.merge(merged_df, cost_of_living[["city", "country",
                    "mcmeal_combo", "avg_monthly_net_salary", "internet_60mbps"]], 
                    on=["city", "country"], how="left")

In [47]:
print(merged_df.shape)

merged_df.isnull().sum()

(289, 36)

city                                0
country                             0
housing                            25
cost of living                     25
startups                           25
venture capital                    25
travel connectivity                25
commute                            25
business freedom                   25
safety                             25
healthcare                         25
education                          25
environmental quality              25
economy                            25
taxation                           25
internet access                    25
leisure & culture                  25
tolerance                          25
outdoors                           25
quality of life index             139
purchasing power index            139
safety index                      139
health care index                 139
cost of living index              139
property price to income ratio    139
traffic commute time index        139
pollution index                   139
climate index                     139
city_ascii                          0
lat                                 0
lng                                 0
iso3                                0
population                          0
mcmeal_combo                       28
avg_monthly_net_salary             28
internet_60mbps                    28
dtype: int64

### Merging with Sunshine Hours

In [48]:
sunshine_hours.columns

Index(['country', 'city', 'sun_jan', 'sun_feb', 'sun_mar', 'sun_apr',
       'sun_may', 'sun_jun', 'sun_jul', 'sun_aug', 'sun_sep', 'sun_oct',
       'sun_nov', 'sun_dec', 'sun_year'],
      dtype='object')

In [49]:
sunshine_hours.replace({"city": {
    "Dar-es-Salaam": "Dar es Salaam",
    "Luxembourg City": "Luxembourg",
    "Chișinău": "Chisinau",
    "Kyiv": "Kiev",
    "Minneapolis": "Minneapolis-Saint Paul",
    "New York City": "New York",
    "OklahomaCity": "Oklahoma City",
    "Portland (OR)": "Portland",
    "Richmond (VA)": "Richmond",
    "Washington,D.C.": "Washington",
    "Brasília": "Brasilia",
    "Rio de Janeiro": "Rio De Janeiro",
    "São Paulo": "Sao Paulo",
    "Bogotá": "Bogota",
    "Medellín": "Medellin",
    "Asunción": "Asuncion",
    }}, inplace=True)

In [50]:
merged_df = pd.merge(merged_df, sunshine_hours[['city', 'country', 'sun_jan', 'sun_feb', 'sun_mar', 'sun_apr',
       'sun_may', 'sun_jun', 'sun_jul', 'sun_aug', 'sun_sep', 'sun_oct',
       'sun_nov', 'sun_dec', 'sun_year']], on=["city", 'country'], how="left")

In [51]:
print(merged_df.shape)

merged_df.isnull().sum()

(289, 49)

city                                0
country                             0
housing                            25
cost of living                     25
startups                           25
venture capital                    25
travel connectivity                25
commute                            25
business freedom                   25
safety                             25
healthcare                         25
education                          25
environmental quality              25
economy                            25
taxation                           25
internet access                    25
leisure & culture                  25
tolerance                          25
outdoors                           25
quality of life index             139
purchasing power index            139
safety index                      139
health care index                 139
cost of living index              139
property price to income ratio    139
traffic commute time index        139
pollution index                   139
climate index                     139
city_ascii                          0
lat                                 0
lng                                 0
iso3                                0
population                          0
mcmeal_combo                       28
avg_monthly_net_salary             28
internet_60mbps                    28
sun_jan                           117
sun_feb                           117
sun_mar                           117
sun_apr                           117
sun_may                           117
sun_jun                           117
sun_jul                           117
sun_aug                           117
sun_sep                           117
sun_oct                           117
sun_nov                           117
sun_dec                           117
sun_year                          117
dtype: int64

### Merging with Average Temperature

In [52]:
avg_temperature.columns

Index(['country', 'city', 'temp_jan', 'temp_feb', 'temp_mar', 'temp_apr',
       'temp_may', 'temp_jun', 'temp_jul', 'temp_aug', 'temp_sep', 'temp_oct',
       'temp_nov', 'temp_dec', 'temp_year', 'temp_ref.'],
      dtype='object')

In [53]:
avg_temperature.replace({"city": {
    "Ngaoundéré":                "N'Gaoundéré",
    "Marrakesh":                 "Marrakech",
    "Zanzibar City":             "Zanzibar",
    "Mek'ele":                   "Mekelle",
    "Addis Ababa":               "Addis Abeba",
    "Reykjavík":                 "Reykjavik",
    "Cracow":                    "Krakow",
    "Zürich":                    "Zurich",
    "Napoli":                    "Naples",
    "Gabès":                     "Gabes",
    "İzmir":                     "Izmir",
    "Florianópolis":             "Florianopolis",
    "Wrocław":                   "Wroclaw",
    "Chișinău":                  "Chisinau",
    "Kyiv":                      "Kiev",
    "São Paulo":                 "Sao Paulo",
    "Bogotá":                    "Bogota",
    "Medellín":                  "Medellin",
    "Brasília":                  "Brasilia",
    "Asunción":                  "Asuncion",
    "Rio de Janeiro":            "Rio De Janeiro",
    "Luxembourg City":           "Luxembourg",
    "New York City":             "New York",
    "Portland (OR)":             "Portland",
    "Minneapolis":               "Minneapolis-Saint Paul",
    "Petropavlovsk-\nKamchatsky": "Petropavlovsk-Kamchatsky",
    "Oklahoma\nCity":            "Oklahoma City",
    "Salt Lake\nCity":           "Salt Lake City",
    "San\nFrancisco":            "San Francisco",
    "Virginia\nBeach":           "Virginia Beach",
    "Washington,\nD.C.":        "Washington",
    }}, inplace=True)

In [54]:
merged_df = pd.merge(merged_df, avg_temperature[['city', 'country', 'temp_jan', 'temp_feb', 'temp_mar', 'temp_apr',
       'temp_may', 'temp_jun', 'temp_jul', 'temp_aug', 'temp_sep', 'temp_oct',
       'temp_nov', 'temp_dec', 'temp_year']], on=["city", "country"], how="left")

In [55]:
print(merged_df.shape)

merged_df.isnull().sum()

(289, 62)

city                0
country             0
housing            25
cost of living     25
startups           25
                 ...
temp_sep          106
temp_oct          106
temp_nov          106
temp_dec          106
temp_year         106
Length: 62, dtype: int64

### Merging with City Happiness

In [56]:
happiness.columns

Index(['city', 'happy_month', 'happy_year', 'happy_decibel_level',
       'happy_traffic_density', 'happy_green_space_area',
       'happy_air_quality_index', 'happy_happiness_score',
       'happy_cost_of_living_index', 'happy_healthcare_index'],
      dtype='object')

In [57]:
happiness.replace({"city": {
    "Panama City":    "Panama",
    "Quebec City": "Quebec",
    "Rio de Janeiro": "Rio De Janeiro",
    "São Paulo": "Sao Paulo",
    "New Delhi": "Delhi",
    }}, inplace=True)

In [58]:
happiness = happiness.sort_values("happy_year", ascending=True).drop_duplicates(subset="city", keep="first")

In [59]:
merged_df = pd.merge(merged_df, happiness[['city', 'happy_decibel_level',
       'happy_traffic_density', 'happy_green_space_area',
       'happy_air_quality_index', 'happy_happiness_score',
       'happy_cost_of_living_index', 'happy_healthcare_index']], on="city", how="left")

In [60]:
print(merged_df.shape)

merged_df.isnull().sum()

(289, 69)

city                            0
country                         0
housing                        25
cost of living                 25
startups                       25
                             ...
happy_green_space_area        197
happy_air_quality_index       197
happy_happiness_score         197
happy_cost_of_living_index    197
happy_healthcare_index        197
Length: 69, dtype: int64

### Merging with Internet Download Speed

In [61]:
internet_speed.columns

Index(['city', 'country', 'country_code', 'continent_code', 'internet_type',
       'median_speed(mbps)'],
      dtype='object')

In [62]:
internet_speed.replace({"city": {
    "São Paulo": "Sao Paulo",
    "Rio de Janeiro": "Rio De Janeiro",
    "Zürich": "Zurich",
    "Melbourne (Greater)": "Melbourne",
    "Kraków": "Krakow",
    "Tel Aviv-Yafo": "Tel Aviv",
    "San José": "San Jose",
    "Medellín": "Medellin",
    "Bogotá": "Bogota",
    }}, inplace=True)

In [63]:
internet_speed[internet_speed["city"] == "Abu Dhabi"]

,city,country,country_code,continent_code,internet_type,median_speed(mbps)
3,Abu Dhabi,United Arab Emirates,AE,AS,mobile,325.39
167,Abu Dhabi,United Arab Emirates,AE,AS,fixed_broadband,308.52

In [64]:
internet_speed["internet_type"].value_counts()

internet_type
fixed_broadband    196
mobile             166
Name: count, dtype: int64

In [65]:
broadband = internet_speed[internet_speed["internet_type"] == "broadband"]
mobile    = internet_speed[internet_speed["internet_type"] == "mobile"]

internet_clean = mobile.merge(broadband, on=["city", "country"], how="outer", suffixes=("_mobile", "_broadband"))
internet_clean["median_speed(mbps)"] = internet_clean["median_speed(mbps)_broadband"].fillna(internet_clean["median_speed(mbps)_mobile"])
internet_clean = internet_clean[["city", "country", "median_speed(mbps)"]]

In [66]:
merged_df = pd.merge(merged_df, internet_clean[["city", "country", "median_speed(mbps)"]], 
                      on=["city", "country"], how="left")
merged_df.shape

(289, 70)

In [67]:
print(merged_df.shape)

merged_df.isnull().sum()

(289, 70)

city                            0
country                         0
housing                        25
cost of living                 25
startups                       25
                             ...
happy_air_quality_index       197
happy_happiness_score         197
happy_cost_of_living_index    197
happy_healthcare_index        197
median_speed(mbps)            181
Length: 70, dtype: int64

## Cleaning and Exporting

In [68]:
merged_df

,city,country,housing,cost of living,startups,venture capital,travel connectivity,commute,business freedom,safety,...,temp_dec,temp_year,happy_decibel_level,happy_traffic_density,happy_green_space_area,happy_air_quality_index,happy_happiness_score,happy_cost_of_living_index,happy_healthcare_index,median_speed(mbps)
0,Aarhus,Denmark,6.1315,4.015,2.8270,2.512,3.5360,6.31175,9.940000,9.6165,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abu Dhabi,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325.39
2,Adelaide,Australia,6.3095,4.692,3.1365,2.640,1.7765,5.33625,9.399667,7.9260,...,21.3\n(70.3),17.3\n(63.1),55.0,Low,65.0,45.0,7.8,105.0,90.0,NaN
3,Ahmedabad,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Albuquerque,United States,7.2620,6.059,3.7720,1.493,1.4555,5.05575,8.671000,1.3435,...,2.4\n(36.3),14.0\n(57.2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,Salt Lake City,United States,6.1410,6.172,6.3000,7.090,2.7370,4.57400,8.671000,5.6570,...,−0.8\n(30.5),11.6\n(52.9),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,San Antonio,United States,6.4020,6.683,5.3560,3.530,1.6815,4.96475,8.671000,4.2165,...,11.6\n(52.9),20.8\n(69.5),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,San Diego,United States,2.9335,5.156,8.3505,8.595,2.6220,4.40975,8.671000,6.9330,...,13.9\n(57.1),17.8\n(64.1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,San Francisco,United States,1.0000,2.618,10.0000,10.000,3.6545,4.68725,8.671000,5.7155,...,11.4\n(52.5),14.6\n(58.2),60.0,High,35.0,40.0,7.4,130.0,93.0,NaN
288,Washington,United States,1.2105,3.595,8.7740,8.056,4.5050,4.45700,8.671000,2.1915,...,4.3\n(39.8),14.6\n(58.2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
merged_df.columns

Index(['city', 'country', 'housing', 'cost of living', 'startups',
       'venture capital', 'travel connectivity', 'commute', 'business freedom',
       'safety', 'healthcare', 'education', 'environmental quality', 'economy',
       'taxation', 'internet access', 'leisure & culture', 'tolerance',
       'outdoors', 'quality of life index', 'purchasing power index',
       'safety index', 'health care index', 'cost of living index',
       'property price to income ratio', 'traffic commute time index',
       'pollution index', 'climate index', 'city_ascii', 'lat', 'lng', 'iso3',
       'population', 'mcmeal_combo', 'avg_monthly_net_salary',
       'internet_60mbps', 'sun_jan', 'sun_feb', 'sun_mar', 'sun_apr',
       'sun_may', 'sun_jun', 'sun_jul', 'sun_aug', 'sun_sep', 'sun_oct',
       'sun_nov', 'sun_dec', 'sun_year', 'temp_jan', 'temp_feb', 'temp_mar',
       'temp_apr', 'temp_may', 'temp_jun', 'temp_jul', 'temp_aug', 'temp_sep',
       'temp_oct', 'temp_nov', 'temp_dec', 'temp_year', 'happy_decibel_level',
       'happy_traffic_density', 'happy_green_space_area',
       'happy_air_quality_index', 'happy_happiness_score',
       'happy_cost_of_living_index', 'happy_healthcare_index',
       'median_speed(mbps)'],
      dtype='object')

### Attribute Comparison: Numbeo vs Teleport

| Numbeo | Teleport | Relationship |
|---|---|---|
| Safety Index | Safety | Same concept, different scale |
| Health Care Index | Healthcare | Same concept, different scale |
| Cost of Living Index | Cost of Living | Needs polarity flip |
| Traffic Commute Time Index | Commute | Needs polarity flip |
| Pollution Index | Environmental Quality | Needs polarity flip |
| Property Price to Income Ratio | Housing | Needs polarity flip |
| Purchasing Power Index | Economy | Related, different metric |
| Climate Index | Outdoors | Related, different metric |
| Quality of Life Index | — | Unique to Numbeo |
| — | Startups | Unique to Teleport |
| — | Venture Capital | Unique to Teleport |
| — | Business Freedom | Unique to Teleport |
| — | Education | Unique to Teleport |
| — | Taxation | Unique to Teleport |
| — | Internet Access | Unique to Teleport |
| — | Leisure & Culture | Unique to Teleport |
| — | Tolerance | Unique to Teleport |
| — | Travel Connectivity | Unique to Teleport |

In [70]:
cols_to_drop = [
    "safety index",
    "health care index",
    "cost of living index",
    "traffic commute time index",
    "pollution index",
    "property price to income ratio",
    "quality of life index",  # derived composite, not needed
    "city_ascii"
]

cleaned_df = merged_df.drop(columns=cols_to_drop)

In [82]:
print(cleaned_df.shape)

cleaned_df.isnull().sum()

(289, 62)

city                            0
country                         0
housing                        25
cost of living                 25
startups                       25
                             ...
happy_air_quality_index       197
happy_happiness_score         197
happy_cost_of_living_index    197
happy_healthcare_index        197
median_speed(mbps)            181
Length: 62, dtype: int64

In [72]:
cleaned_df.columns

Index(['city', 'country', 'housing', 'cost of living', 'startups',
       'venture capital', 'travel connectivity', 'commute', 'business freedom',
       'safety', 'healthcare', 'education', 'environmental quality', 'economy',
       'taxation', 'internet access', 'leisure & culture', 'tolerance',
       'outdoors', 'purchasing power index', 'climate index', 'lat', 'lng',
       'iso3', 'population', 'mcmeal_combo', 'avg_monthly_net_salary',
       'internet_60mbps', 'sun_jan', 'sun_feb', 'sun_mar', 'sun_apr',
       'sun_may', 'sun_jun', 'sun_jul', 'sun_aug', 'sun_sep', 'sun_oct',
       'sun_nov', 'sun_dec', 'sun_year', 'temp_jan', 'temp_feb', 'temp_mar',
       'temp_apr', 'temp_may', 'temp_jun', 'temp_jul', 'temp_aug', 'temp_sep',
       'temp_oct', 'temp_nov', 'temp_dec', 'temp_year', 'happy_decibel_level',
       'happy_traffic_density', 'happy_green_space_area',
       'happy_air_quality_index', 'happy_happiness_score',
       'happy_cost_of_living_index', 'happy_healthcare_index',
       'median_speed(mbps)'],
      dtype='object')

In [73]:
cleaned_df.to_csv("data/final/full_dataset_nan.csv", index=False)
cleaned_df.to_json("data/final/full_dataset_nan.json", orient="records")

### Preserving the most columns

In [74]:
cleaned_df_columns = cleaned_df.drop(columns=[
    'happy_decibel_level', 'happy_traffic_density',
    'happy_green_space_area', 'happy_air_quality_index',
    'happy_happiness_score', 'happy_cost_of_living_index',
    'happy_healthcare_index', 'median_speed(mbps)', 
    'purchasing power index', 'climate index'
])

cleaned_df_columns.shape

(289, 52)

In [75]:
cleaned_df_columns.isnull().sum()

city                        0
country                     0
housing                    25
cost of living             25
startups                   25
venture capital            25
travel connectivity        25
commute                    25
business freedom           25
safety                     25
healthcare                 25
education                  25
environmental quality      25
economy                    25
taxation                   25
internet access            25
leisure & culture          25
tolerance                  25
outdoors                   25
lat                         0
lng                         0
iso3                        0
population                  0
mcmeal_combo               28
avg_monthly_net_salary     28
internet_60mbps            28
sun_jan                   117
sun_feb                   117
sun_mar                   117
sun_apr                   117
sun_may                   117
sun_jun                   117
sun_jul                   117
sun_aug                   117
sun_sep                   117
sun_oct                   117
sun_nov                   117
sun_dec                   117
sun_year                  117
temp_jan                  106
temp_feb                  106
temp_mar                  106
temp_apr                  106
temp_may                  106
temp_jun                  106
temp_jul                  106
temp_aug                  106
temp_sep                  106
temp_oct                  106
temp_nov                  106
temp_dec                  106
temp_year                 106
dtype: int64

In [76]:
cleaned_df_columns.dropna(inplace=True)
cleaned_df_columns.shape

(138, 52)

In [83]:
cleaned_df_columns.isnull().sum()

city                      0
country                   0
housing                   0
cost of living            0
startups                  0
venture capital           0
travel connectivity       0
commute                   0
business freedom          0
safety                    0
healthcare                0
education                 0
environmental quality     0
economy                   0
taxation                  0
internet access           0
leisure & culture         0
tolerance                 0
outdoors                  0
lat                       0
lng                       0
iso3                      0
population                0
mcmeal_combo              0
avg_monthly_net_salary    0
internet_60mbps           0
sun_jan                   0
sun_feb                   0
sun_mar                   0
sun_apr                   0
sun_may                   0
sun_jun                   0
sun_jul                   0
sun_aug                   0
sun_sep                   0
sun_oct                   0
sun_nov                   0
sun_dec                   0
sun_year                  0
temp_jan                  0
temp_feb                  0
temp_mar                  0
temp_apr                  0
temp_may                  0
temp_jun                  0
temp_jul                  0
temp_aug                  0
temp_sep                  0
temp_oct                  0
temp_nov                  0
temp_dec                  0
temp_year                 0
dtype: int64

In [77]:
cleaned_df_columns.to_csv("data/final/columns_dataset.csv", index=False)
cleaned_df_columns.to_json("data/final/columns_dataset.json", orient="records")

### Preserving City

In [78]:
cleaned_df_cities = cleaned_df.drop(columns=[
       'happy_decibel_level', 'happy_traffic_density',
       'happy_green_space_area', 'happy_air_quality_index',
       'happy_happiness_score', 'happy_cost_of_living_index',
       'happy_healthcare_index', 'median_speed(mbps)', 
       'purchasing power index', 'climate index', 'sun_jan', 'sun_feb',
       'sun_mar', 'sun_apr', 'sun_may', 'sun_jun', 'sun_jul', 'sun_aug',
       'sun_sep', 'sun_oct', 'sun_nov', 'sun_dec', 'sun_year', 'temp_jan',
       'temp_feb', 'temp_mar', 'temp_apr', 'temp_may', 'temp_jun', 'temp_jul',
       'temp_aug', 'temp_sep', 'temp_oct', 'temp_nov', 'temp_dec', 'temp_year'
])   

cleaned_df_cities.shape

(289, 26)

In [79]:
cleaned_df_cities.isnull().sum()

city                       0
country                    0
housing                   25
cost of living            25
startups                  25
venture capital           25
travel connectivity       25
commute                   25
business freedom          25
safety                    25
healthcare                25
education                 25
environmental quality     25
economy                   25
taxation                  25
internet access           25
leisure & culture         25
tolerance                 25
outdoors                  25
lat                        0
lng                        0
iso3                       0
population                 0
mcmeal_combo              28
avg_monthly_net_salary    28
internet_60mbps           28
dtype: int64

In [80]:
cleaned_df_cities.dropna(inplace=True)

cleaned_df_cities.shape

(238, 26)

In [84]:
cleaned_df_cities.isnull().sum()

city                      0
country                   0
housing                   0
cost of living            0
startups                  0
venture capital           0
travel connectivity       0
commute                   0
business freedom          0
safety                    0
healthcare                0
education                 0
environmental quality     0
economy                   0
taxation                  0
internet access           0
leisure & culture         0
tolerance                 0
outdoors                  0
lat                       0
lng                       0
iso3                      0
population                0
mcmeal_combo              0
avg_monthly_net_salary    0
internet_60mbps           0
dtype: int64

In [81]:
cleaned_df_cities.to_csv("data/final/cities_dataset.csv", index=False)
cleaned_df_cities.to_json("data/final/cities_dataset.json", orient="records")